type L = [string, ...string[]];

const languages: L = [
  "Auto",
  "Algerian Arabic",
  "Amharic",
  "Assamese",
  "Azerbaijani",
  "Bavarian",
  "Bengali",
  "Bhojpuri",
  "Burmese",
  "Cantonese",
  "Cebuano",
  "Chhattisgarhi",
  "Chittagonian",
  "Czech",
  "Deccan",
  "Dutch",
  "Eastern Punjabi",
  "Egyptian Arabic",
  "English",
  "Farsi",
  "French",
  "Gan Chinese",
  "German",
  "Greek",
  "Gujarati",
  "Hakka",
  "Hausa",
  "Hejazi Arabic",
  "Hindi",
  "Hungarian",
  "Indonesian",
  "Italian",
  "Javanese",
  "Jin Chinese",
  "Kannada",
  "Kazakh",
  "Khmer",
  "Kinyarwanda",
  "Korean",
  "Malayalam",
  "Malaysian",
  "Magahi",
  "Maithili",
  "Marathi",
  "Mesopotamian Arabic",
  "Min Bei Chinese",
  "Min Dong Chinese",
  "Moroccan Arabic",
  "Nepali",
  "Nigerian Fulfulde",
  "Northern Kurdish",
  "Northern Pashto",
  "Northern Uzbek",
  "Odia",
  "Persian",
  "Polish",
  "Portuguese",
  "Romanian",
  "Russian",
  "Rundi",
  "Saʽidi Arabic",
  "Sanaani Spoken Arabic",
  "Saraiki",
  "Sindhi",
  "Sinhalese",
  "Somali",
  "South Azerbaijani",
  "South Levantine Arabic",
  "Southern Min",
  "Southern Pashto",
  "Spanish",
  "Sudanese Arabic",
  "Sunda",
  "Sylheti",
  "Tagalog",
  "Tamil",
  "Taʽizzi-Adeni Arabic",
  "Telugu",
  "Thai",
  "Tunisian Arabic",
  "Turkish",
  "Ukrainian",
  "Urdu",
  "Uyghur",
  "Vietnamese",
  "Western Punjabi",
  "Wu Chinese",
  "Yoruba",
  "Zhuang",
];

export default languages;
